apiVersion: v1
kind: Service
metadata:
  name: {{ include "ofeed.webServiceName" . }}
  labels:
    {{- include "ofeed.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "ofeed.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
